# Generated by Django 4.0 on 2022-01-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
    ]
